# Generated by Django 3.2.2 on 2021-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
