# Generated by Django 3.2.2 on 2021-05-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_post_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='Category_id',
        ),
    ]
