# Generated by Django 3.2.2 on 2021-05-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_category_post_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category_id',
            new_name='Category',
        ),
    ]
