# Generated by Django 3.2.2 on 2021-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
